<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class MovieTitlesSeeder extends Seeder
{
    public function run(): void
    {
        $movies = [

            // ==================== ALOHIDA KINOLAR ====================
            [
                'code'       => '26',
                'name'       => 'Singam: 3 (2024) [720p]',
                'channel_id' => '-1003605893088',
                'message_id' => 889,
                'file_id'    => 'BAACAgQAAyEFAATW7Y_gAAM9aYxeYckypeZ2NJtFxuWqPNk25lYAAlsUAAL0cUBThoqls-xpKgo6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '27',
                'name'       => 'Muqaddas zamin [480p]',
                'channel_id' => '-1003605893088',
                'message_id' => 890,
                'file_id'    => 'BAACAgIAAxkBAAIDemmPYKSsh1cOvsVuRiUaFo8r1EenAAKNeQACGcgQSwSQmugOt-WTOgQ',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '38',
                'name'       => 'Nomi yo‘q (lekin yoq ekan 😆)',
                'channel_id' => '-1003605893088',
                'message_id' => 901,
                'file_id'    => 'BAACAgIAAxkBAAIDhWmPYKRvxTz6vkPaFwrWsdgonXVuAAJTWgACMjNhSDMMc-kKsFmaOgQ',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '39',
                'name'       => 'Qimorga tikilgan qiz',
                'channel_id' => '-1003605893088',
                'message_id' => 902,
                'file_id'    => 'BAACAgIAAxkBAAIDhmmPYKQHljnhIeF8mQfiHjTnYEPUAAJcYwAC2PAISmgokfxVcgt0OgQ',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '40',
                'name'       => 'Deliha 2 (2024) — 2-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 903,
                'file_id'    => 'BAACAgIAAxkBAAIDh2mPYKSzr34zP9JmCxu2J9qXhQ75AAI0IgACVBgAAUkJmgIouYeamToE',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '42',
                'name'       => 'Novda (o‘zbek filmi)',
                'channel_id' => '-1003605893088',
                'message_id' => 905,
                'file_id'    => 'BAACAgIAAxkBAAIDiWmPYKRq5QK21-tQFHZBTsggqywqAALZDwACqqsQSiAL3esRzpKqOgQ',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '43',
                'name'       => 'Mexanik 2',
                'channel_id' => '-1003605893088',
                'message_id' => 906,
                'file_id'    => 'BAACAgQAAxkBAAIDimmPYKRO7Jn6xd1ilndhflVNLBoVAAKSCgAC9iKhUB2l8sXxT7niOgQ',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '47',
                'name'       => 'Mening qizim',
                'channel_id' => '-1003605893088',
                'message_id' => 909,
                'file_id'    => 'BAACAgQAAxkBAAIDjWmPYKRKoNefztunDmJsKB44ocp3AALTCgAChUgQUcYfysTe73nhOgQ',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '48',
                'name'       => 'Vaqt (Premyera)',
                'channel_id' => '-1003605893088',
                'message_id' => 910,
                'file_id'    => 'BAACAgIAAxkBAAIDjmmPYKS9ggTn6PSecNSfetnsi4ifAAL4DQAC2px4SfGhpP7cPz2vOgQ',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '50',
                'name'       => 'Super agentlar',
                'channel_id' => '-1003605893088',
                'message_id' => 912,
                'file_id'    => 'BAACAgEAAxkBAAIDkGmPYKQpp3K2Kd6hiyOAkEnJwSCZAAJvAgACHt55RLk26ZkyVRzBOgQ',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '51',
                'name'       => 'Danki',
                'channel_id' => '-1003605893088',
                'message_id' => 913,
                'file_id'    => 'BAACAgQAAxkBAAIDkWmPYKRFGInjC5V6XfbYct1V8QX6AALYFQACgzKYUnxP3Ydc6pQmOgQ',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // ==================== JUMONG SERIALI (to‘liq) ====================
            [
                'code'       => '56',
                'name'       => 'Jumong afsonasi — 1-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 93,
                'file_id'    => 'BAACAgIAAxkBAAPeaYbXzYr_4nypHlTD-JmvmAo8ynQAApwRAAKYhVBI7UL00cm2NLA6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '57',
                'name'       => 'Jumong afsonasi — 2-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 94,
                'file_id'    => 'BAACAgIAAxkBAAPfaYbXzXBpoRClTT-9oMGwQX6JRdMAAqARAAKYhVBIxV2MOEm4WIQ6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '58',
                'name'       => 'Jumong afsonasi — 3-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 95,
                'file_id'    => 'BAACAgIAAxkBAAPgaYbXzepGVwABeJjnig2EfvFfjxOCAAKhEQACmIVQSEJMb3VUJjEJOgQ',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '59',
                'name'       => 'Jumong afsonasi — 4-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 96,
                'file_id'    => 'BAACAgIAAxkBAAPhaYbXzaoyPKcw1mbo3Winf4nv8xYAAqMRAAKYhVBI3fegz7vsxPM6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '60',
                'name'       => 'Jumong afsonasi — 5-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 97,
                'file_id'    => 'BAACAgIAAxkBAAPiaYbXzTaLWcTZxBKBTajOuCFRBIcAAjYKAAIik0lLmI69Ty0fuWc6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '61',
                'name'       => 'Jumong afsonasi — 6-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 98,
                'file_id'    => 'BAACAgIAAxkBAAPjaYbXze7L1MKyT5y5imHeZupH8lQAAk0JAAIik1FLCtM2lYu4eAM6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '62',
                'name'       => 'Jumong afsonasi — 7-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 99,
                'file_id'    => 'BAACAgIAAxkBAAPkaYbXzcYyCLccsuBgJc3iqvrWBD0AAiAIAAJGclBL6cUiYNeco0I6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '63',
                'name'       => 'Jumong afsonasi — 8-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 100,
                'file_id'    => 'BAACAgIAAxkBAAPlaYbXzag_PGhr_H5lIqscythNOoUAAj0MAAL2V1BLLoY1M364xpE6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '64',
                'name'       => 'Jumong afsonasi — 9-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 101,
                'file_id'    => 'BAACAgIAAxkBAAPmaYbXzZXz_DmiTNKH0mUrXtK__FsAAm0JAAJGclBLw3Z7taLrkZw6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '65',
                'name'       => 'Jumong afsonasi — 10-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 102,
                'file_id'    => 'BAACAgIAAxkBAAPnaYbXzfrh8l-D9zVkwOkHURW-ZHAAAuM4AAJa7dhI48XAo0WV7Lo6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '66',
                'name'       => 'Jumong afsonasi — 11-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 103,
                'file_id'    => 'BAACAgIAAxkBAAPoaYbXza-kGESPyYHiVUeishs3HjwAAoMKAAJ7fFFLAVRr9RR7GTI6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '67',
                'name'       => 'Jumong afsonasi — 12-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 104,
                'file_id'    => 'BAACAgIAAxkBAAPpaYbXzZ5Mye8VcyV6H57yp-_IonsAAokQAAIhIUlL9NUsiVYNp-M6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '68',
                'name'       => 'Jumong afsonasi — 13-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 105,
                'file_id'    => 'BAACAgIAAxkBAAPqaYbXzQABO8J6BHsjZjbKvRqMqB4AAxoKAAJGclBLmEeflLZPqjw6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '69',
                'name'       => 'Jumong afsonasi — 14-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 106,
                'file_id'    => 'BAACAgIAAxkBAAPraYbXzVFy2q1l9UupF7EgtqJl6_IAAgMLAAJ7fFFLIJfBgsNFF446BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '70',
                'name'       => 'Jumong afsonasi — 15-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 107,
                'file_id'    => 'BAACAgIAAxkBAAPsaYbXzaOHTkaDYB6dQcm_VcR_LFgAAr8KAAI_CVFLeiYJyfqg8yc6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '71',
                'name'       => 'Jumong afsonasi — 17-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 108,
                'file_id'    => 'BAACAgIAAxkBAAPtaYbXzTUoT_5DOf_uS4XoyUVE2awAApALAAIik1FLoVBqKG76fb46BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '72',
                'name'       => 'Jumong afsonasi — 18-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 109,
                'file_id'    => 'BAACAgIAAxkBAAPuaYbXzRymYhZi4UV_JdtdGQ69nR8AAkoLAAIO81FLN1nyFripPts6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '73',
                'name'       => 'Jumong afsonasi — 19-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 110,
                'file_id'    => 'BAACAgIAAxkBAAPvaYbXzaoRUNrpKin-rPv8xjDLW98AAj4LAAI_CVFLZBLeIhBOPaI6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '74',
                'name'       => 'Jumong afsonasi — 20-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 111,
                'file_id'    => 'BAACAgIAAxkBAAPwaYbXzZORQpSgpkwh7bARigsC_NMAAvMLAAJ7fFFLeojdQytSrrM6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '75',
                'name'       => 'Jumong afsonasi — 21-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 112,
                'file_id'    => 'BAACAgIAAxkBAAPxaYbXzRfMZpUU6bWNfmotr5x7BVYAAiwPAAL2V1BLsNMVwsdn7qE6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '76',
                'name'       => 'Jumong afsonasi — 22-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 113,
                'file_id'    => 'BAACAgIAAxkBAAPyaYbXzbjvMk0pOHg9sUCIBj3X-HIAAqMKAAIhIVFLNWJanaZBYnU6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '77',
                'name'       => 'Jumong afsonasi — 23-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 114,
                'file_id'    => 'BAACAgIAAxkBAAPzaYbXzVGtlfNd58enc56n67MxzuYAAqAKAAJtNFhL6LDKD5a24hY6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '78',
                'name'       => 'Jumong afsonasi — 24-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 115,
                'file_id'    => 'BAACAgIAAxkBAAP0aYbXzYPdr1gXHxHf-x-xkpf7VEAAApoJAAJBtFhLGzc2uNE8zMo6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '79',
                'name'       => 'Jumong afsonasi — 25-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 116,
                'file_id'    => 'BAACAgIAAxkBAAP1aYbXzXjWELVinhRbq-iXmgi5hp4AAsMLAALdVVlLGNHYv-KKQRo6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '80',
                'name'       => 'Jumong afsonasi — 26-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 117,
                'file_id'    => 'BAACAgIAAxkBAAP2aYbXzV1JWBOUhZqsn7AIFuydYTUAAm8KAAIzWFhLKXIyQnbHbvQ6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '81',
                'name'       => 'Jumong afsonasi — 27-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 118,
                'file_id'    => 'BAACAgIAAxkBAAP3aYbXzbaQvrbie8iLcVmUF9kCCfoAAlcLAAIzWFhLnCF6Es5GvhA6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '82',
                'name'       => 'Jumong afsonasi — 28-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 119,
                'file_id'    => 'BAACAgIAAxkBAAP4aYbXzdoraE6Uu9nLq7y9OSdPMv8AAkoKAAIh21hLxFpvqc8G2Lw6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '83',
                'name'       => 'Jumong afsonasi — 29-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 120,
                'file_id'    => 'BAACAgIAAxkBAAP5aYbXzU-0NLa73Gk2BlsbHCQM7R4AAjEMAAKJB1lLUfrZUfgvovw6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '84',
                'name'       => 'Jumong afsonasi — 30-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 121,
                'file_id'    => 'BAACAgIAAxkBAAP6aYbXzUkefq571BJKx5gyj5FjXS4AAmYIAAJtNGBLZsJDuNE0yko6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '85',
                'name'       => 'Jumong afsonasi — 31-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 122,
                'file_id'    => 'BAACAgIAAxkBAAP7aYbXzUgEuogU6MWoLLkKlHifQ_EAAh8MAAIzWFhL4jvy5nxKGZY6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '86',
                'name'       => 'Jumong afsonasi — 32-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 123,
                'file_id'    => 'BAACAgIAAxkBAAP8aYbXzZB9LXMGmbY4LhbSbwSF2mUAAjILAAJLuVlLcJ_lhLLvcC06BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '87',
                'name'       => 'Jumong afsonasi — 33-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 124,
                'file_id'    => 'BAACAgIAAxkBAAP9aYbXzXva3_DzCrbeaPnkJR4f0YIAAmgMAAIzWFhLMeVJM7ke8eM6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '88',
                'name'       => 'Jumong afsonasi — 34-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 125,
                'file_id'    => 'BAACAgIAAxkBAAP-aYbXzf3ijvsSf8B3kLHFwV-RXUQAAnQMAAIh22BLePOCyy3Rgx06BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '89',
                'name'       => 'Jumong afsonasi — 35-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 126,
                'file_id'    => 'BAACAgIAAxkBAAP-aYbXzcOj09uqwT2C9sVz-JEtWC4AAikPAAJLuWFLEW5Jui5S-146BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '90',
                'name'       => 'Jumong afsonasi — 36-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 127,
                'file_id'    => 'BAACAgIAAxkBAAP_aYbXzSbqXuZSNhPv1g7qMuXe51oAAnAOAAJQeMBILKTR0bSq_Pg6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '91',
                'name'       => 'Jumong afsonasi — 37-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 128,
                'file_id'    => 'BAACAgIAAxkBAAIBAWmG182pDZf_8ZnVfM10w6RSZUWGAALeDgACM1hgS1ctYVakN3WQOgQ',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '92',
                'name'       => 'Jumong afsonasi — 38-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 129,
                'file_id'    => 'BAACAgIAAxkBAAIBAmmG180MAAH0YLUKEsGHMVm4IjXSyAAC_QwAAt1VYUtnJAejPZzmRjoE',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '93',
                'name'       => 'Jumong afsonasi — 39-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 130,
                'file_id'    => 'BAACAgIAAxkBAAIBA2mG181X45W2nlml-zvcPFWgNHASAAJmDwACM1hgS0Ywhd4Fb1owOgQ',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '94',
                'name'       => 'Jumong afsonasi — 40-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 131,
                'file_id'    => 'BAACAgIAAxkBAAIBBGmG182QUNjyuSDdTnwAAcvBmj2wQwACwAoAAm00aEvW4fyyK2lGjjoE',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '95',
                'name'       => 'Jumong afsonasi — 41-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 132,
                'file_id'    => 'BAACAgIAAxkBAAIBBWmG183YX5me9w_bjh8NyNRr2MckAAJ9CQACQbRoS-PWhILTfrxtOgQ',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '96',
                'name'       => 'Jumong afsonasi — 42-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 133,
                'file_id'    => 'BAACAgIAAxkBAAIBBmmG183C809HokEcDeYlu610fINjAAJ8DgAC3VVhS_JOiiFEyBb4OgQ',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '97',
                'name'       => 'Jumong afsonasi — 43-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 134,
                'file_id'    => 'BAACAgIAAxkBAAIBB2mG1807qWKZH1O40lA-9X8WicrFAAKfBgACbdxpS0n07okmb3d6OgQ',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '98',
                'name'       => 'Jumong afsonasi — 44-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 135,
                'file_id'    => 'BAACAgIAAxkBAAIBCGmG1801ciBKUc1ju4H_-MhU-yz4AAI5CgACuGpoS1J2Hn43t1M3OgQ',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '99',
                'name'       => 'Jumong afsonasi — 45-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 136,
                'file_id'    => 'BAACAgIAAxkBAAIBCWmG180akAFrIYA4zkcWkDaoalq_AAJUCAACwUVpS64ZMIPsy4G_OgQ',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '100',
                'name'       => 'Jumong afsonasi — 46-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 137,
                'file_id'    => 'BAACAgIAAxkBAAIBCmmG182SocqZHBI3t3MlhqMBfX6vAAI0CgACwUVpSwQwwHJp8TMjOgQ',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '101',
                'name'       => 'Jumong afsonasi — 47-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 138,
                'file_id'    => 'BAACAgIAAxkBAAIBC2mG182uVC6fffoYKi2OFIY6H4ypAAKWDwACLiZpS7l2YHJryw4rOgQ',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '102',
                'name'       => 'Jumong afsonasi — 48-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 139,
                'file_id'    => 'BAACAgIAAxkBAAIBDGmG182eo5uYA5ZQ4J_tsrHIUN2-AAIDBwACLiZxS0U84PaXBUHnOgQ',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '103',
                'name'       => 'Jumong afsonasi — 49-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 140,
                'file_id'    => 'BAACAgIAAxkBAAIBDWmG181I5bR9WRGWqgU9vq0_omWtAAKADQACwUVpS37Z73AGerZeOgQ',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '104',
                'name'       => 'Jumong afsonasi — 50-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 141,
                'file_id'    => 'BAACAgIAAxkBAAIBDmmG1814GbYmu1Q1MS-hWmiP0WvfAAKBBwACLiZxS_BxR4dGe0YpOgQ',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '105',
                'name'       => 'Jumong afsonasi — 51-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 142,
                'file_id'    => 'BAACAgIAAxkBAAIBD2mG182QnqiJkW_1BFZcK-_xUpmeAALnCAACvHZwSwxOE4FHMg-fOgQ',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '106',
                'name'       => 'Jumong afsonasi — 52-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 143,
                'file_id'    => 'BAACAgIAAyEFAATW7Y_gAAOPaYbWCbn2RtBY8IQdp-NQBk-gd4MAAvwKAAKA9nFL41tWTSkIASQ6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '107',
                'name'       => 'Jumong afsonasi — 53-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 144,
                'file_id'    => 'BAACAgIAAyEFAATW7Y_gAAOQaYbWG_9wye3NsxKlJMNZKaEJlzgAAhILAAKA9nFLn8_NDEeqEEE6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '108',
                'name'       => 'Jumong afsonasi — 54-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 145,
                'file_id'    => 'BAACAgIAAyEFAATW7Y_gAAORaYbWJVZVS6tvRzJ6V8l8IlbJvgUAAoIJAAIR1nBL_3phrE1zdgY6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '109',
                'name'       => 'Jumong afsonasi — 55-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 146,
                'file_id'    => 'BAACAgIAAyEFAATW7Y_gAAOSaYbWLniK6q2Kba6y3QKV4bYFWogAAqIMAAK4anBLb4eLAddX40Y6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '110',
                'name'       => 'Jumong afsonasi — 56-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 147,
                'file_id'    => 'BAACAgIAAyEFAATW7Y_gAAOTaYbWOhdtIwFOe8XXvbwXcm8iiuwAAswQAAJQeLhI0YOyrbUWInE6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '114',
                'name'       => 'Jumong afsonasi — 59-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 150,
                'file_id'    => 'BAACAgIAAyEFAATW7Y_gAAOWaYbWXuE-ujL5HErsnmSq2UQcU2MAAnQOAAJQeMBI_v1JyNnUuVU6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '117',
                'name'       => 'Jumong afsonasi — 64-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 154,
                'file_id'    => 'BAACAgIAAyEFAATW7Y_gAAObaYbWjx7Rlw-7Dai9FEcNAAE5hcDWAALjDgACbdxxS_Lp4FEvAz2yOgQ',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '119',
                'name'       => 'Jumong afsonasi — 66-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 156,
                'file_id'    => 'BAACAgIAAyEFAATW7Y_gAAOdaYbWqAv4s0Th0YAL6ndzPv3GQjkAAjUIAAIaRBhKy4qOiPe_VpQ6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '120',
                'name'       => 'Jumong afsonasi — 67-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 157,
                'file_id'    => 'BAACAgIAAyEFAATW7Y_gAAOeaYbWveL8ODUEc-5GYhfTU6y-ruoAAvwJAAJO-XhLDkZ5KznBpwQ6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '121',
                'name'       => 'Jumong afsonasi — 68-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 158,
                'file_id'    => 'BAACAgIAAyEFAATW7Y_gAAOfaYbWyQcuUuMCdg6Cm1gDB4MMJM8AAj4KAAJF83hLhxjfAknK6AU6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '122',
                'name'       => 'Jumong afsonasi — 69-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 159,
                'file_id'    => 'BAACAgIAAyEFAATW7Y_gAAOgaYbW1-37xaE3zy8auxBFnbgc0OkAAoEKAAJO-XhL6nOXCxv7xwo6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '123',
                'name'       => 'Jumong afsonasi — 70-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 160,
                'file_id'    => 'BAACAgIAAyEFAATW7Y_gAAOhaYbW4g-c04tkQEULuIeLvCKmv9YAAp4KAAJF83hLHu-_v2Kultw6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '124',
                'name'       => 'Jumong afsonasi — 71-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 161,
                'file_id'    => 'BAACAgIAAyEFAATW7Y_gAAOiaYbW8a3cfG9EqP_KXDvQwyxIZFkAAo0MAAIKanhL5RHK8Fl3nB06BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '125',
                'name'       => 'Jumong afsonasi — 72-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 162,
                'file_id'    => 'BAACAgIAAyEFAATW7Y_gAAOjaYbW-3GqPkCsWavuRJJMcIDslDgAAswHAAIiioFL19wcmRHaYbY6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '126',
                'name'       => 'Jumong afsonasi — 73-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 163,
                'file_id'    => 'BAACAgIAAyEFAATW7Y_gAAOkaYbXCPJjZ-qTf3_zuJZlTCDCj6oAAvEHAAIiioFLW3gSOKnmEUw6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '127',
                'name'       => 'Jumong afsonasi — 74-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 164,
                'file_id'    => 'BAACAgIAAyEFAATW7Y_gAAOlaYbXEXsEaCRvRXSd2nNYm16R6FcAAhAJAAJO-YBLVNFGIt5DQZ46BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '128',
                'name'       => 'Jumong afsonasi — 75-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 165,
                'file_id'    => 'BAACAgIAAyEFAATW7Y_gAAOmaYbXHSJy5320OCyjbRYFC-zHFlMAAnQLAAIhMoFLUNL2CyaRahs6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '130',
                'name'       => 'Jumong afsonasi — 77-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 167,
                'file_id'    => 'BAACAgIAAyEFAATW7Y_gAAOoaYbXL2Ms4_TmcjG0Q5Kpj8jomE8AAn8JAAJJBLBL6uKlgRQ6aJw6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '131',
                'name'       => 'Jumong afsonasi — 78-qism',
                'channel_id' => '-1003605893088',
                'message_id' => 168,
                'file_id'    => 'BAACAgIAAyEFAATW7Y_gAAOpaYbXOXrjeLXpPogI28-Q2da_UaIAAtYLAAJMh7FLR2kPWRmE9zI6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '132',
                'name'       => 'Jumong afsonasi — 79-80-qism (Final)',
                'channel_id' => '-1003605893088',
                'message_id' => 169,
                'file_id'    => 'BAACAgIAAyEFAATW7Y_gAAOqaYbXQzh3pW_3DdVgtpzvWZCDsOgAAooFAAJIIhlLGPfrEp2GVQw6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '133',
                'name'       => 'Jumong afsonasi — 81-qism (Oxirgi)',
                'channel_id' => '-1003605893088',
                'message_id' => 170,
                'file_id'    => 'BAACAgIAAyEFAATW7Y_gAAOraYbXU5sR22J9HLlS2JjJ6G34DIkAAq4NAALECdBLAe4aswMAAToxOgQ',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // ==================== OXIRGI YANGI KINOLAR ====================
            [
                'code'       => '136',
                'name'       => 'Kuzatuvchilar',
                'channel_id' => '-1003605893088',
                'message_id' => 995,
                'file_id'    => 'BAACAgQAAyEFAATW7Y_gAAIBIWmMcT2V2Y-vR212M6LyAAFSCo48fQACFR0AAqPHWFCvHMB3QQx5fToE',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '137',
                'name'       => 'Furiosa: Telba Maks Solnomasi (2024)',
                'channel_id' => '-1003605893088',
                'message_id' => 299,
                'file_id'    => 'BAACAgQAAyEFAATW7Y_gAAIBJWmMcT3BYXscs2KLVWt48J3DFoK_AALGGgACaquIUvo-54F4swG8OgQ',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '138',
                'name'       => 'Nomi yo‘q kino (140-kod)',
                'channel_id' => '-1003605893088',
                'message_id' => 301,
                'file_id'    => 'BAACAgQAAyEFAATW7Y_gAAIBLGmMcwNnoi_9WVCNpz5_MQABKKrnhQACySEAAhW7WFMOqGLG0qcz9joE',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '139',
                'name'       => 'Grenlandiya 2: Migratsiya (2026)',
                'channel_id' => '-1003605893088',
                'message_id' => 302,
                'file_id'    => 'BAACAgIAAyEFAATW7Y_gAAIBLmmOJN8rb0lgOHnH8w4teX-5n0bTAALAlwACevRYSAGQv_dQwgmpOgQ',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '140',
                'name'       => 'Qasoskor qiz',
                'channel_id' => '-1003605893088',
                'message_id' => 303,
                'file_id'    => 'BAACAgQAAyEFAATW7Y_gAAIBL2mOJN8qd8iCCl5U69dvtGvDyb8uAAJhCwACVBpZU9msHcluyTKKOgQ',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '141',
                'name'       => 'Telba maks: G‘azab yo‘li',
                'channel_id' => '-1003605893088',
                'message_id' => 304,
                'file_id'    => 'BAACAgQAAyEFAATW7Y_gAAIBH2mMb-o-f9i_Qy9HXj9SkJNv4oLPAAKoHgACyUTYU64lZj9BuainOgQ',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '142',
                'name'       => 'Jigar 3',
                'channel_id' => '-1003605893088',
                'message_id' => 307,
                'file_id'    => 'BAACAgIAAyEFAATW7Y_gAAIBM2mPRrkqbRNVWUVRi3vcya4NyyO2AAKMjwACEgtpSHynwsb4Gs8dOgQ',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '143',
                'name'       => 'Irlandiyalik',
                'channel_id' => '-1003605893088',
                'message_id' => 306,
                'file_id'    => 'BAACAgEAAyEFAATW7Y_gAAIBMmmPRrk7lkDsDMg6B_XYTKhgsYLJAAJeAANV7JhHWB_TmqdZ5VE6BA',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '144',
                'name'       => 'Parijdagi akula',
                'channel_id' => '-1003605893088',
                'message_id' => 305,
                'file_id'    => 'BAACAgQAAyEFAATW7Y_gAAIBMWmPRrkhhfwsu9GRrjybOhZ8rpUYAAJHFAAC-L6QU1VEhYFuE6SSOgQ',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code'       => '145',
                'name'       => 'Yangi kino (145-kod)',
                'channel_id' => '-1003605893088',
                'message_id' => 308,
                'file_id'    => 'BAACAgIAAyEFAATW7Y_gAAIBNGmPSMwlM_Vye1G5fOb7u3UvrQ4_AAKekAACX_xwSDbY4Py6uLGjOgQ',
                'views'      => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        // Katta hajmda xavfsiz insert
        foreach (array_chunk($movies, 50) as $chunk) {
            DB::table('movies')->insert($chunk);
        }

        $this->command->info(count($movies) . " ta kino to‘g‘rilangan holda qo‘shildi!");
    }
}